[versions]
kotlin = "1.7.10"

[libraries]
inquirer = "com.github.kotlin-inquirer:kotlin-inquirer:0.1.0"
guava = "com.google.guava:guava:31.1-jre"
jansi = "org.fusesource.jansi:jansi:2.4.0"
serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
